### ISSUE TITLE
tag a new release?

### ISSUE THREAD

**Issue by jrobeson** [walac/pyusb#110]
There's been some important fixes since the last release last year. Is there any reason not to mark it stable yet?

**Comment by walac** [comment]
I have to make the code thread safe before tagging release candidate 1. I just don't have time to do that right now.

**Comment by jrobeson** [comment]
ok, understood. thanks

**Comment by jrobeson** [comment]
can you tag a new beta then?

**Comment by walac** [comment]
I just pushed thread safe patch, rc1 will hopefully be released soon.
