### ISSUE TITLE
set_configuration fails if called with invalid configuration

### ISSUE THREAD

**Issue by karlp** [walac/pyusb#111]
We were trying to use set_configuration for testing device firmware behaviour, as https://github.com/libopencm3/libopencm3/pull/473#issuecomment-132964467

It's completely reasonable that pyusb validates that the configuration is valid before attempting to send the control request, we're ok with using the raw ctrl_transfer interface.  However, https://github.com/walac/pyusb/blob/master/usb/core.py#L129 tries to access the "cfg" object when util.find_descriptor just returned None above.

This then fails with "AttributeError: 'NoneType' object has no attribute 'bConfigurationValue'"

It should fail, yes, but I don't think it should fail like that :)

**Comment by walac** [comment]
Fixed, thanks.
