### ISSUE TITLE
set_configuration() when device is already configured

### ISSUE THREAD

**Issue by myorbit** [walac/pyusb#122]
I had a problem recently when calling set_configuration(). Take this code for example using libusb-1.0:
```python
dev = usb.core.find(idVendor=ID_VENDOR, idProduct=ID_PRODUCT)
dev.set_configuration()
dev.write(0x01, '\x01', 100)
```
I was not able to write to my device because I received a timeout.
For a test I removed `dev.set_configuration()` and writing/reading is possible.

Calling `dev.get_active_configuration()` I found out that my device was already in a configured state. Reading further in the [libusb documentation](http://libusb.org/static/api-1.0/group__dev.html#ga186593ecae576dad6cd9679f45a2aa43) I found: 
>If you call this function on a device already configured with the selected configuration, then this function will act as a lightweight device reset: it will issue a SET_CONFIGURATION request using the current configuration, causing most USB-related device state to be reset (altsetting reset to zero, endpoint halts cleared, toggles reset).

This is exactly what happens to my USB device. 

My device has only one configuration and one interface. Why is my device already in a configured state without issuing a `set_configuration()`? Which part puts my device into a configured state? Does this only happen to USB devices with only one configuration and one interface?

The solution is easy as suggested in http://libusb.org/static/api-1.0/caveats.html: Check with `get_active_configuration()` if it is already configured and if yes what is the active configuration number.

This also might be a big issue for PyUSB beginners.

**Comment by walac** [comment]
You might want to submit a PR for the [faq](https://github.com/walac/pyusb/blob/master/docs/faq.rst) doc.
