### ISSUE TITLE
dfu write [Errno 32] Pipe error

### ISSUE THREAD

**Issue by zarya** [walac/pyusb#127]
./md380-dfu write ./patches/2.032/unwrapped.img
4e011006 
.
[Errno 32] Pipe error

./md380-dfu write firmware/D002.034.bin 
4e011006 
..
[Errno 32] Pipe error

**Comment by walac** [comment]
Hi, could you please elaborate more on the error you have? Pipe error generally means either a device specific protocol error, or a firmware bug.

**Comment by zarya** [comment]
Owh woops posted in the wrong project Sorry
