### ISSUE TITLE
AssertionError assert ep is not None

### ISSUE THREAD

**Issue by Future-Home** [walac/pyusb#163]
![assert error](https://cloud.githubusercontent.com/assets/23623768/20911729/c8f06fd4-bb72-11e6-8120-48fec2873165.png)
Maybe I am missing someting, but I am trying to connect to a USB connected device, but get AssertionError.

**Comment by walac** [comment]
You have an IN endpoint and you are searching for an OUT endpoint, the result is as expected, None.
