### ISSUE TITLE
still beta?

### ISSUE THREAD

**Issue by ulrichard** [walac/pyusb#59]
Hi, is pyusb really still beta, or is it release worthy by now? 
The reason I'm asking is because I'd like to package https://github.com/btchip/btchip-python for debian/ubuntu. It depends on pyusb (>= 1.0). 
There is a debian package python-usb but it's at version 0.4.3. 
https://packages.debian.org/wheezy/python-usb
The maintainer wrote that he prefers not to package beta grade software.

**Comment by walac** [comment]
Stable version has been released.
