### ISSUE TITLE
Exception when script using pyusb finishes

### ISSUE THREAD

**Issue by devbisme** [walac/pyusb#66]
When my script executes `sys.exit()`, I get an exception:

`Exception AttributeError: "'NoneType' object has no attribute 'copy'" in <bound method Device.__del__ of <usb.core.Device object at 0x029F09D0>> ignored`

I traced this to the `release_all_interfaces()` method in core.py. It tries to copy `self._claimed_intf`, but in my case this happens to be an empty set and the exception occurs. I stopped this error by putting in a test for `len(self._claimed_intf) == 0`.

Am I making an error in how I'm using pyusb? Or is this an error in core.py?

I'm using pyusb-1.0.0b1 with python 2.7.6 and libusb-1.0 on Windows 7.

**Comment by Toilal** [comment]
Thanks @walac ! Keep on the good job on this library :)

**Comment by krissen** [comment]
I might misunderstand something, but the patch was merged into master, right? I've built and installed master, but on python 3.4 I'm getting the same error as reported here.

```
libusb: warning [libusb_close] internal signalling write failed, closing anyway
```

**Comment by krissen** [comment]
Ping @walac (see comment above).

**Comment by walac** [comment]
@krissen Sorry for the delay, can you reproduce the issue in a test script and post it here?

**Comment by krissen** [comment]
No problem (re: delay)! Hmm. Unfortunately I don't write python, but I'll head over to Tigge/antfs-cli#129 and ask @Tigge if he could assist me.
