### ISSUE TITLE
Cannot find any devices

### ISSUE THREAD

**Issue by yangzhe** [walac/pyusb#77]
I tried to use 

usb.core.find(find_all=True)

but I cannot find any devices.  I do have several usb devices plugged in. I was using python 2.7 and pyusb 1.0.0.b2 with win7. Thanks.

**Comment by walac** [comment]
No reply, closing it.

**Comment by scholi** [comment]
Hi,
I have just installed pyusb v 1.0.2 on Windows 64bits using python 3.6.1 64bit.

I cannot find any device somehow.

```python

import time
import usb.core
import usb.util

VID = 0x403
PID = 0x6001

devs = list(usb.core.find(find_all=True))
print(devs)

dev = usb.core.find(idVendor=VID, idProduct=PID)
print(dev)
```

The above code will print be an empty array and a None for dev. Am I missing something?

Thank you for your help and kind regards

scholi

**Comment by mcuee** [comment]
You have to install supported driver and libusb-1.0. Please read the FAQ for more details.
