### ISSUE TITLE
Backends are reimported each time find() is called with backend parameter None

### ISSUE THREAD

**Issue by rabryan** [walac/pyusb#79]
If find() is called multiple times with backend=None, the backend is reimported and consequently the backend library is reinitalized.  For libusb, this results in libusb_init() and libusb_exit() getting called on each call to find() and renders the backend module's mechanism for caching the library (i.e. the global "_lib" variable) useless.

On windows, this was somehow leading to the intermittent "Access Denied" errors as detailed here: http://sourceforge.net/p/pyusb/mailman/message/33076849/

An easy workaround is for the caller to get the specific backend once, cache it themselves, and pass it explicitly.

**Comment by walac** [comment]
`get_backend` [returns a new `LibUSB1` object](https://github.com/walac/pyusb/blob/master/usb/backend/libusb1.py#L915), which [calls `libusb_init` in its constructor](https://github.com/walac/pyusb/blob/master/usb/backend/libusb1.py#L684).

So, I am afraid that caching the imported backed will not fix your issue either. A better solution would be you call [`libusb1.get_backend`](https://github.com/walac/pyusb/blob/master/usb/backend/libusb1.py#L909) yourself, cache the returned object and pass it to `find` through the `backend` argument.

**Comment by rabryan** [comment]
Yep.  That's what I'm doing at it works fine.
