### ISSUE TITLE
read data in iso mode seems calling intr_read

### ISSUE THREAD

**Issue by QianJin2013** [walac/pyusb#81]
hi, i find iso_read seems not works correctly.<br>
core.py:<br>
        fn_map = {<br>
                    util.ENDPOINT_TYPE_BULK:backend.bulk_read,<br>
                    util.ENDPOINT_TYPE_INTR:backend.intr_read,<br>
                    util.ENDPOINT_TYPE_ISO:backend.iso_read<br>
                }<br>
        ...<br>
        fn = fn_map[util.endpoint_type(ep.bmAttributes)]<br>

when ep.bmAttributes is 1, it should means iso_read, but this set seems not ordered correctly. According to debug log, it's using intr_read..... <br>
Am i right?

**Comment by walac** [comment]
Hi,

I tested on my local environment and it works here. The order doesn't matter, since it is map structure. Could you please pot your code and the output of `lsusb -vv` for your device?

**Comment by QianJin2013** [comment]
thank you for your test!!!.  I will try it again.

2015-01-01 23:55 GMT+09:00 Wander Lairson Costa <notifications@github.com>:

**Comment by walac** [comment]
Works for me.

**Comment by QianJin2013** [comment]
Thank you. I seems I was wrong somewhere. Now works

2015年1月18日日曜日、Wander Lairson Costa<notifications@github.com>さんは書きました:
