### ISSUE TITLE
readme.md could mention that pip is supported

### ISSUE THREAD

**Issue by patrickmmartin** [walac/pyusb#82]
I used  

    pushd c:\Python27\Scripts && pip install pyusb==1.0.0b2 && popd

to install - I saw the issue where installing with 'pip install pyusb' with no version will not work until the version is out of beta, so please consider pluggin this approach as the installation method

**Comment by walac** [comment]
I don't mention pip in the [README](https://github.com/walac/pyusb/blob/master/README.rst) file because it is supported in the contribution mode.

**Comment by arve0** [comment]
Can you elaborate what you mean by 
> in the contribution mode.

Any reason why pip is not the recommended way of installation?

**Comment by patrickmmartin** [comment]
well pip works, but at the time of testing, not without an explicit version no., which is not 100% obvious

**Comment by walac** [comment]
By *contribution mode* I mean that people that don't fully work (and don't have obligation to) on the project kindly push releases to pip. Currently I cannot work on it, but there is a big demand for it, so I will see if I change this and push to pip whenever a new version is released.
